baseURL = "https://miguelvf.dev/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Miguel Villa Floran"
#paginate = 10
enableRobotsTXT = true
enableEmoji = true
enableInlineShortcodes = true
pluralizeListTitles = false
# Enable to calculate the last modified date from Git history and show it in the post header
#enableGitInfo = true

[build]
  noJSConfigInAssets = true
  [build.buildStats]
    # With each build, Hugo writes a hugo_stats.json file that contains arrays
    # of the class attributes, id attributes, and tags of each HTML element
    # within the published site. For production builds, this file is required
    # by PurgeCSS to prune unused CSS.
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This setting allows inlining <script> and <style> tags in markdown,
      # which is useful and required to use Prism plugins, but may be dangerous
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP image processing quality, defaults to 75%
  quality = 90

[params]
  # Description to display on homepage
  description = "Curious, Creative, and Clever. A programmer, robotics enthusiast, and continuous learner."
  
  # Theme color for browsers
  themeColorSEO = "#D8C787"

  # Keywords relevant for SEO
  metaKeywords = ["miguel villa floran", "miguel vf", "miguel villa", "kaweees", "kiwis", "blog", "robotics"]

  # Default theme, overriden by local storage and OS preferences
  defaultTheme = "dark"

  # Magnitude of the theme contrast, can be "light", "medium", or "dark"
  themeContrast = "medium"

  author = "Miguel Villa Floran"
  
  subtitle = "Home"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "c",
      "cpp",
      "javascript",
      "bash",
      "diff",
      "yaml",
      "bash",
      "makefile",
      "toml",
      "python",
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]
  
  # By default, the theme creates resized versions of images ranging from 300 to
  # 700 pixels wide in increments of 200 pixels
  #[params.imageResize]
  #  min = 300
  #  max = 700
  #  increment = 200
  
  [params.tagCloud]
    enable = false
    minFontSizeRem = 0.8
    maxFontSizeRem = 2.0

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "cv"
    name = "Resume"
    url = "/resume"
    weight = 20

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params.jsonResume]
      present = "present"
