baseURL = "https://miguelvf.dev/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Miguel Villa Floran"

# theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "native"

[params]
  # Description to display on homepage
  description = "Curious, Creative, and Clever. A programmer, robotics enthusiast, and continuous learner.""

  # URL for the avatar on homepage
  avatarURL = "logo.png"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  themeColor = "#D8C787"

  # Keywords relevant for SEO
  metaKeywords = ["miguel villa floran", "miguel vf", "miguel villa", "kaweees", "kiwis", "blog", "robotics"]

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
