baseURL = "https://miguelvf.dev/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Miguel Villa Floran"
# theme = "gokarna"
copyright = "Miguel Villa Floran"

# Automatically generate robots.txt
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "native"

[params]
  # Description to display on homepage
  description = "Curious, Creative, and Clever. A programmer, robotics enthusiast, and continuous learner."

  # URL for the avatar on homepage
  avatarURL = "logo.png"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  themeColor = "#D8C787"

  # Keywords relevant for SEO
  metaKeywords = ["miguel villa floran", "miguel vf", "miguel villa", "kaweees", "kiwis", "blog", "robotics"]

[menu]
  [[menu.main]]
    name = "About"
    pre = ""
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[sitemap]
  changefreq = 'hourly'
  filename = 'sitemap.xml'
  priority = 0.5